-- DATE MATH

SELECT birthdate, DATEDIFF(CURDATE(), birthdate) FROM people; -- to find number of days between 2 dates

SELECT DATE_ADD(CURDATE(), INTERVAL 1 YEAR);

SELECT DATE_ADD(CURDATE(), INTERVAL 12 YEAR);

SELECT DATE_ADD(CURDATE(), INTERVAL 1 MONTH);

SELECT DATE_SUB(CURDATE(), INTERVAL 1 MONTH);

SELECT birthdate, DATE_ADD(birthdate, INTERVAL 18 YEAR) FROM people;

-- TIME MATH

SELECT TIMEDIFF(CURTIME(), '07:00:00');